---
all:
  hosts:
    vm_1:
      ansible_host: 158.160.60.95
    vm_2:
      ansible_host: 158.160.121.167
    vm_3:
      ansible_host: 158.160.120.115
  vars:
    ansible_user: pma
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_become: true
    ansible_become_password: "!69"
