- name: Обновление пакетов
  hosts: all
  roles:
    - role: aptupdate
      tags: [aptu]

- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: apps
      tags: [apps]

- name: Установка nginx
  hosts: all
  roles:
    - role: nginx
      tags: [nginx]
